// <auto-generated />
using System;
using App.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250928212930_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Models.Brand", b =>
                {
                    b.Property<int>("IdBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBrand");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBrand"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("brandName");

                    b.HasKey("IdBrand");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.HasIndex("IdBrand")
                        .IsUnique();

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("App.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idProduct");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduct"));

                    b.Property<int>("ActualStock")
                        .HasColumnType("integer")
                        .HasColumnName("actualStock");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<int?>("IdBrand")
                        .HasColumnType("integer")
                        .HasColumnName("idBrand");

                    b.Property<int?>("IdTypeProduct")
                        .HasColumnType("integer")
                        .HasColumnName("idTypeProduct");

                    b.Property<int>("MaxStock")
                        .HasColumnType("integer")
                        .HasColumnName("maxStock");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer")
                        .HasColumnName("minStock");

                    b.Property<string>("PhotoName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("photoName");

                    b.Property<string>("PhotoUri")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoUri");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("productName");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdProduct")
                        .IsUnique();

                    b.HasIndex("IdTypeProduct");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("Product");
                });

            modelBuilder.Entity("App.Models.TypeProduct", b =>
                {
                    b.Property<int>("IdTypeProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTypeProduct");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduct"));

                    b.Property<string>("TypeProductName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("typeProductName");

                    b.HasKey("IdTypeProduct");

                    b.HasIndex("IdTypeProduct")
                        .IsUnique();

                    b.HasIndex("TypeProductName")
                        .IsUnique();

                    b.ToTable("TypeProduct");
                });

            modelBuilder.Entity("App.Models.Product", b =>
                {
                    b.HasOne("App.Models.Brand", "NavigationBrand")
                        .WithMany("Products")
                        .HasForeignKey("IdBrand")
                        .HasConstraintName("FK_product_brand");

                    b.HasOne("App.Models.TypeProduct", "NavigationTypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("IdTypeProduct")
                        .HasConstraintName("FK_product_type");

                    b.Navigation("NavigationBrand");

                    b.Navigation("NavigationTypeProduct");
                });

            modelBuilder.Entity("App.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("App.Models.TypeProduct", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
